[book]
authors = ["Evalf"]
language = "en"
multilingual = false
src = "src"
title = "The Nutils Book"

[output.html]
git-repository-url = "https://github.com/evalf/nutils-book"
cname = "nutils.org"

[preprocessor.katex]
after = ["links"]
