name: github pages
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install mdbook
      run: |
        cargo install mdbook --no-default-features
    - name: Install mdbook-katex
      run: |
        cargo install mdbook-katex
    - name: Build book
      run: |
        mdbook build -d docs
    - name: Deploy GitHub Pages
      if: github.event_name == 'push'
      run: |
        git add docs
        git config user.name "Github Pages"
        git config user.email ""
        git commit -m "Deploy to gh-pages"
        git push -f origin main:gh-pages
